name: hello-world
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-and-test-dev:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set Up Java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Step 3: Build the Project
      - name: Build Project
        run: mvn clean install

        
      - name: my-step
        run: echo "Hello World!"
